name: build

on:
  push:
  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc
          - clang
        arch:
          - x86
          - x64

    steps:
      - uses: actions/checkout@v3

      - name: Dependencies
        run: |
          sudo apt-get install g++-multilib
          sudo python3 -m pip install pyperf

      - name: Build and run
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=Release -DGCC_ARCH=${{ matrix.arch }} ..
          make
          sudo pyperf system tune && ./perf


  MacOS:
    runs-on: macos-11

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          # - arm64 # Github MacOS host use Intel CPUs and cannot run arm code

    steps:
      - uses: actions/checkout@v3

      - name: Dependencies
        run: |
          sudo python3 -m pip install pyperf

      - name: Build and run
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DOSX_ARCH=${{ matrix.arch }} ..
          make
          sudo pyperf system tune && ./perf


  Windows_MSVC:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        arch:
          - Win32
          - x64

    steps:
      - uses: actions/checkout@v3

      - name: Dependencies
        run: |
          python3 -m pip install pyperf

      - name: Build and run
        run: |
          mkdir build
          cd build
          cmake -G 'Visual Studio 17 2022' -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
          pyperf system tune
          .\Release\perf


  # Windows_MingW: # MingW on Github CI does not fully support 32 bits: link fails when it tries to link 64 bits system libraries.
  #   runs-on: windows-2022

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       build_type:
  #         - debug
  #         - release
  #       arch:
  #         - x64
  #         # - Win32

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: actions/checkout@v3
  #       with:
  #         repository: ocornut/imgui
  #         path: imgui

  #     - name: Configure
  #       shell: bash
  #       run: cmake -G 'MinGW Makefiles' -DGCC_ARCH=${{ matrix.arch }} -B cmake-build -S .github

  #     - name: Build
  #       shell: bash
  #       run: cmake --build cmake-build --parallel $NUMBER_OF_PROCESSORS

  #     - name: Run (MingW)
  #       run: .\cmake-build\example_implot.exe
  